name: carrot
description: Another take on a widget library with an opiniated theme.
version: 1.0.0-dev.0
homepage: https://github.com/basmilius/flutter-carrot

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^10.1.1
  intl: ^0.18.0
  provider: ^6.0.5
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  generate: true
  uses-material-design: false
