name: carrot
description: A new Flutter UI library.
version: 1.0.0-dev
homepage: https://github.com/basmilius/flutter-carrot

environment:
  sdk: ">=2.17.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  go_router: ^4.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: false
