name: carrot
description: A new Flutter UI library.
version: 1.0.0+1
homepage: https://vegetable.studio/carrot

environment:
  sdk: ">=2.17.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  go_router: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: false
