name: carrot
description: Another take on a widget library with an opiniated theme.
version: 1.0.0-dev.0
homepage: https://github.com/basmilius/flutter-carrot

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  go_router: ^5.2.0
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: false
